baseURL = "localhost:1313"
languageCode = "en-us"
title = "ABRA"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.76.5"

[build]
# Used by PurgeCSS
writeStats = true

# The site's parameters
[params]
home = "Home"
abbreviatedTitle = "ABRA"
description = "Artificial Biology, Robots & Art"
favicon = "img/favicon.png"

## Homepage image. Different sizes can be used to provide responsiveness.
homepageimageset = [{img = "img/homepage_480w.jpg", width = "480w", maxwidth = "800px"},
	{img = "img/homepage_960w.jpg", width = "960w", maxwidth = "1440px"},
	{img = "img/homepage_1920w.jpg", width = "1920w", maxwidth = ""}]
homepageimagefallback = "img/homepage_960w.jpg"
homepageimagealt = "Neurons artwork homepage image. CC0 Geralt/Pixabay id-582054"

lenslogo = "img/lens-journal-logo.png"

twittercard = "summary_large_image"
twitterhandle = "@epistemehealth"
socialimage = "img/twittercard.jpg"
socialimagealt = "Logo"
socialdescription = "Health Sciences Journal Description"

## Set to true to load libraries from Cloudflare and Tailwind CDNs where available. Otherwise leave blank.
useCDN = true

## Custom blocks for the footer
customblocks = [{ name = "Custom Block", content = "Website footer custom block."},
{name = "Erasmus+", content = "Here maybe some logo with a short description"},
{name = "Privacy Notice", content = "The only user information collected from this website is in the form of log files generated the site's [hosting provider](https://www.netlify.com/privacy/)."},
{name = "Contact Us", content = "Place to group all of the necessary contact"}]

footercontent = "Footer content."

[privacy]
[privacy.googleAnalytics]
	disable = true
[privacy.disqus]
	disable = true
[privacy.instagram]
	disable = true
[privacy.twitter]
	disable = true
[privacy.vimeo]
	disable = true
[privacy.youtube]
	disable = true

[[Languages.en.menu.main]]
	weight = 2
	name = "Articles"
	url = "article"
[[Languages.en.menu.main]]
	weight = 3
	name = "Events"
	url = "events"
[[Languages.en.menu.main]]
	weight = 4
	name = "News"
	url = "news"
[[Languages.en.menu.main]]
	weight = 5
	name = "Outputs"
	hasChildren = true
[[Languages.en.menu.main]]
	parent = "Outputs"
	name = "Curriculum"
	url = "outputs/curriculum"
	weight = 6
[[Languages.en.menu.main]]
	parent = "Outputs"
	name = "Workshops"
	url = "outputs/workshops"
	weight = 7
[[Languages.en.menu.main]]
	parent = "Outputs"
	name = "Blog"
	url = "blog"
	weight = 8
# ITALIAN NAVIGATION --------------------
[[Languages.it.menu.main]]
	weight = 2
	name = "[IT] Articles"
	url = "article"
[[Languages.it.menu.main]]
	weight = 3
	name = "[IT] Events"
	url = "events"
[[Languages.it.menu.main]]
	weight = 4
	name = "[IT] News"
	url = "news"
[[Languages.it.menu.main]]
	weight = 5
	name = "[IT] Outputs"
	hasChildren = true
[[Languages.it.menu.main]]
	parent = "Outputs"
	name = "[IT] Curriculum"
	url = "outputs/curriculum"
	weight = 6
[[Languages.it.menu.main]]
	parent = "Outputs"
	name = "[IT] Workshops"
	url = "outputs/workshops"
	weight = 7
[[Languages.it.menu.main]]
	parent = "Outputs"
	name = "[IT] Blog"
	url = "blog"
	weight = 8
# HUNGARIAN NAVIGATION
[[Languages.hu.menu.main]]
	weight = 2
	name = "[HU] Articles"
	url = "article"
[[Languages.hu.menu.main]]
	weight = 3
	name = "[HU] Events"
	url = "events"
[[Languages.hu.menu.main]]
	weight = 4
	name = "[HU] News"
	url = "news"
[[Languages.hu.menu.main]]
	weight = 5
	name = "[HU] Outputs"
	hasChildren = true
[[Languages.hu.menu.main]]
	parent = "Outputs"
	name = "[HU] Curriculum"
	url = "outputs/curriculum"
	weight = 6
[[Languages.hu.menu.main]]
	parent = "Outputs"
	name = "[HU] Workshops"
	url = "outputs/workshops"
	weight = 7
[[Languages.hu.menu.main]]
	parent = "Outputs"
	name = "[HU] Blog"
	url = "blog"
	weight = 8
# FINNISH NAVIGATION
[[Languages.fi.menu.main]]
	weight = 2
	name = "[fi] Articles"
	url = "article"
[[Languages.fi.menu.main]]
	weight = 3
	name = "[fi] Events"
	url = "events"
[[Languages.fi.menu.main]]
	weight = 4
	name = "[fi] News"
	url = "news"
[[Languages.fi.menu.main]]
	weight = 5
	name = "[fi] Outputs"
	hasChildren = true
[[Languages.fi.menu.main]]
	parent = "Outputs"
	name = "[fi] Curriculum"
	url = "outputs/curriculum"
	weight = 6
[[Languages.fi.menu.main]]
	parent = "Outputs"
	name = "[fi] Workshops"
	url = "outputs/workshops"
	weight = 7
[[Languages.fi.menu.main]]
	parent = "Outputs"
	name = "[fi] Blog"
	url = "blog"
	weight = 8

[taxonomies]
  keyword = "keywords"

[languages]
  [[en]]
	languageName= "English"
	languageCode = "en-us"
	weight= 1
  [[hu]]
	languageName= "Hungarian"
	weight= 2
	customblocks = [{ name = "[HU] Custom Block", content = "[HU] Website footer custom block."},
  {name = "[HU] Erasmus+", content = "[HU] Here maybe some logo with a short description"},
  {name = "[HU] Privacy Notice", content = "[HU] The only user information collected from this website is in the form of log files generated the site's [hosting provider](https://www.netlify.com/privacy/)."},
  {name = "[HU] Contact Us", content = "[HU] Place to group all of the necessary contact"}]
	[[it]]
	languageName= "Italian"
	weight= 3
	customblocks = [{ name = "[IT] Custom Block", content = "[IT] Website footer custom block."},
  {name = "[IT] Erasmus+", content = "[IT] Here maybe some logo with a short description"},
  {name = "[IT] Privacy Notice", content = "[IT] The only user information collected from this website is in the form of log files generated the site's [hosting provider](https://www.netlify.com/privacy/)."},
  {name = "[IT] Contact Us", content = "[IT] Place to group all of the necessary contact"}]
  [[fi]]
	languageName= "Finnish"
	weight= 4
	customblocks = [{ name = "[FI] Custom Block", content = "[FI] Website footer custom block."},
  {name = "[FI] Erasmus+", content = "[FI] Here maybe some logo with a short description"},
  {name = "[FI] Privacy Notice", content = "[FI] The only user information collected from this website is in the form of log files generated the site's [hosting provider](https://www.netlify.com/privacy/)."},
  {name = "[FI] Contact Us", content = "[FI] Place to group all of the necessary contact"}]
