baseURL = "https://abra-hub.net"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "ABRA"
theme = ["hugo-social-metadata"]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.76.5"

[build]
# Used by PurgeCSS
writeStats = true

# The site's parameters
[params]
description = "Artificial Biology, Robots & Art"
keywords = "robotics, artificial, biology, education, transdisciplinary, content" # TODO SEO
twitterUsername = "@your_twitter_username" #TODO
socialImage = "path/to/the/twitter/card/image" # TODO
home = "Home"
abbreviatedTitle = "ABRA"
# googleAnalytics = "UA-111111111111-1"
canonifyURLs = true
# copyright = "Author"
enableRobotsTXT = true
favicon = "/img/favicon.png"
logo = "/img/logo_a.png"
logoInverted = "/img/logo_b.png"

## Homepage image. Different sizes can be used to provide responsiveness.
homepageimageset = [{img = "/img/homepage_480w.jpg", width = "480w", maxwidth = "800px"},
	{img = "/img/homepage_960w.jpg", width = "960w", maxwidth = "1440px"},
	{img = "/img/homepage_1920w.jpg", width = "1920w", maxwidth = ""}]
homepageimagefallback = "img/homepage_960w.jpg"
homepageimagealt = "Neurons artwork homepage image. CC0 Geralt/Pixabay id-582054"

## TODO: Social Media
# twittercard = "summary_large_image"
# twitterhandle = "@epistemehealth"
# socialimage = "img/twittercard.jpg"
# socialimagealt = "Logo"
# socialdescription = "Health Sciences Journal Description"
## Set to true to load libraries from Cloudflare and Tailwind CDNs where available. Otherwise leave blank.
useCDN = true
## Custom blocks for the footer
customblocks = [{ name = "Custom Block", content = "Website footer custom block."},
{name = "Erasmus+", content = "Here maybe some logo with a short description"},
{name = "Privacy Notice", content = "The only user information collected from this website is in the form of log files generated the site's [hosting provider](https://www.netlify.com/privacy/)."},
{name = "Contact Us", content = "Place to group all of the necessary contact"}]
footercontent = "Footer content."


[privacy]
[privacy.googleAnalytics]
	disable = true
[privacy.disqus]
	disable = true
[privacy.instagram]
	disable = true
[privacy.twitter]
	disable = true
[privacy.vimeo]
	disable = true
[privacy.youtube]
	disable = true

[[Languages.en.menu.main]]
	weight = 1
	name = "About"
	url = "about"
[[Languages.en.menu.main]]
	weight = 2
	name = "Blog"
	url = "blog"
[[Languages.en.menu.main]]
	weight = 3
	name = "Team"
	url = "team"
[[Languages.en.menu.main]]
	weight = 4
	name = "Calendar"
	url = "calendar"


# ITALIAN NAVIGATION --------------------
[[Languages.it.menu.main]]
	weight = 1
	name = "About"
	url = "about"
[[Languages.it.menu.main]]
	weight = 2
	name = "Blog"
	url = "blog"
[[Languages.it.menu.main]]
	weight = 3
	name = "Team"
	url = "team"
[[Languages.it.menu.main]]
	weight = 4
	name = "Calendar"
	url = "calendar"

# HUNGARIAN NAVIGATION
[[Languages.hu.menu.main]]
	weight = 1
	name = "About"
	url = "about"
[[Languages.hu.menu.main]]
	weight = 2
	name = "Blog"
	url = "blog"
[[Languages.hu.menu.main]]
	weight = 3
	name = "Team"
	url = "team"
[[Languages.hu.menu.main]]
	weight = 4
	name = "Calendar"
	url = "calendar"

# FINNISH NAVIGATION
[[Languages.fi.menu.main]]
	weight = 1
	name = "About"
	url = "about"
[[Languages.fi.menu.main]]
	weight = 2
	name = "Blog"
	url = "blog"
[[Languages.fi.menu.main]]
	weight = 3
	name = "Team"
	url = "team"
[[Languages.fi.menu.main]]
	weight = 4
	name = "Calendar"
	url = "calendar"

# Danish NAVIGATION
[[Languages.dk.menu.main]]
	weight = 1
	name = "About"
	url = "about"
[[Languages.dk.menu.main]]
	weight = 2
	name = "Blog"
	url = "blog"
[[Languages.dk.menu.main]]
	weight = 3
	name = "Team"
	url = "team"
[[Languages.dk.menu.main]]
	weight = 4
	name = "Calendar"
	url = "calendar"

[taxonomies]
  keyword = "keywords"

[languages]
	[[en]]
	languageName= "English"
	languageCode = "en-us"
	weight= 1
	[[hu]]
	languageName= "Hungarian"
	weight= 2
	[[it]]
	languageName= "Italian"
	weight= 3
	[[fi]]
	languageName= "Finnish"
	weight= 4
	[[dk]]
	languageName= "Danish"
	weight= 5
